const InputItem = [
  {
    title: '會員帳號',
    type: 'text',
    preset: '請輸入會員帳號',
    name: 'account',
    max: '20',
    min: '4',
    req: true,
  },
  {
    title: '會員密碼',
    type: 'password',
    preset: '請輸入會員密碼',
    name: 'password',
    max: '12',
    min: '6',
    req: true,
  },
  {
    title: '確認密碼',
    type: 'password',
    preset: '請再次輸入會員密碼',
    name: 'rePassword',
    max: '12',
    min: '6',
    req: true,
  },
  {
    title: '會員姓名',
    type: 'text',
    preset: '請輸入會員姓名',
    name: 'name',
    max: '',
    min: '',
    req: true,
  },
  {
    title: 'E-mail',
    type: 'text',
    preset: '請輸入電子信箱',
    name: 'email',
    max: '',
    min: '',
    req: true,
  },
  {
    title: '連絡電話',
    type: 'text',
    preset: '請輸入連絡電話',
    name: 'phone',
    max: '',
    min: '',
    req: true,
  },
  {
    title: '銀行代碼（二手商品收款用，非必填）',
    type: 'text',
    preset: '',
    name: 'bankcode',
    max: '',
    min: '',
    req: false,
  },
  {
    title: '銀行帳號（二手商品收款用，非必填）',
    type: 'text',
    preset: '',
    name: 'bankaccount',
    max: '',
    min: '',
    req: false,
  },
];

export default InputItem;
